#!/bin/bash
#
# Author: Sebastiaan Meijer (sebastiaanmeijer.nl)
#
# Copy this file to /etc/libvirt/hooks/qemu
# Make sure to mark it executable with "chmod +x /etc/libvirt/hooks/qemu"

GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

BASEDIR="$(dirname $0)"

HOOKPATH="$BASEDIR/qemu.d/$GUEST_NAME/$HOOK_NAME/$STATE_NAME"

set -e # If a script exits with an error, we should as well.

# check if it's a non-empty executable file
if [ -f "$HOOKPATH" ] && [ -s "$HOOKPATH" ] && [ -x "$HOOKPATH" ]; then
    eval \"$HOOKPATH\" "$@"
elif [ -d "$HOOKPATH" ]; then
    while read file; do
        # check for no file named "*"
        if [ ! -z "$(echo "$file" | grep "*")" ]; then break; fi

        # check if it's a non-empty executable file
        if [ -f "$file" ] && [ -s "$file" ] && [ -x "$file" ]; then
            eval \"$file\" "$@"
        fi
    done <<< "$(find -L "$HOOKPATH" -maxdepth 1 -type f -executable -print;)"
fi
